### PR TITLE
Issues #5 #6 #7

### PR DESCRIPTION
**Pull request by nightroman**

### CODE REVIEW

**Comment by nightroman** [comment]
Hello?

**Comment by cspotcode** [comment]
Thank you very much for the reminder.  Is TabExpansion2 built in to PowerShell?  If so, this all looks good and I'll merge and push a new version to the gallery.

**Comment by cspotcode** [comment]
Published as v0.8.1.  Thanks for the PR!  I credited you in the changelog.

**Comment by nightroman** [comment]
Thank you!

Meanwhile, I moved forward with fixes and improvements. Please take a look at my lab:

- [branch 03-ok](https://github.com/nightroman/PS-GuiCompletion/tree/03-ok) - this what I would suggest to accept in a further series of PRs
- [04-my-filter](https://github.com/nightroman/PS-GuiCompletion/tree/04-my-filter) - this is probably not for everyone but I am going to use this, perhaps I will create a permanent clone

Please review, try and let me know what you think.

**Comment by cspotcode** [comment]
@nightroman Thanks, I won't have any time to review these until after the weekend, but I'm particularly excited to look at the filtering changes you've made.

I made you a collaborator on this repository; please feel free to push these branches here.  Also, if you want, I can create a GitHub organization for us to share.  A shared home for nifty PowerShell modules could be useful for other projects, too.

Regarding your new filtering behavior, even if it does not become a default behavior, we can always put it behind a flag.  Or if it's better than the current behavior, we can make yours the default and put the legacy behavior behind a flag.

**Comment by nightroman** [comment]
I will put my changes in order and push them to the main repo, one way or another. I would like to get some feedback from you at first. Please take your time, there is no hurry.

**Pull request merged**
