### PR TITLE
Major improvements in UX and performance and fixes of known issues.

### PR DESCRIPTION
**Pull request by nightroman**
- Use top and bottom margins
- Remake Out-ConsoleList as Get-ConsoleList without ineffective pipeline
- Remake New-TabItem without pipeline input
- Cache and use $Host.UI.RawUI as module scope $UI
- Replace slow ForEach-Object with faster loops
- Replace New-Box property bag with variables, comment out not used
- Remove not used $HasChild and fix not initialized error
- Fix `Right Arrow` wrong index and out-of-range
- Treat * and ? in filter as wildcards
- Fix strict mode failures
- Use ShiftPressed flag. Remove not used/needed Get-KeyState.
- Cache $Colors for faster access and shorter code
- Use MinimumTextWidth and remake Get-ContentSize: -- avoids the status line is wider than the list -- completion menus normally have some limit (ISE)
- Use CompletionResult as is, retire New-TabItem

### CODE REVIEW

**Comment by nightroman** [comment]
This branch contains major changes and improvement but without changes in "philosophy" of the tool and UX (unlike the branch nightroman-2 with further development). Please, review and if it's fine then let's continue from this point.

**Comment by cspotcode** [comment]
I'm finally taking a look at this and fixing a couple bugs myself.  So far so good.

I see you fixed some "strict mode" failures.  Can we call `Set-StrictMode` at the top of this module?

**Comment by cspotcode** [comment]
What do you think about requiring Powershell v5 or newer?  The class syntax would really clean up some of this code.

**Comment by nightroman** [comment]
> I see you fixed some "strict mode" failures. Can we call Set-StrictMode at the top of this module?

It is known to be not safe for production code. We may call some user code at some point. We may not require it to be designed for the strict mode. In fact, some PowerShell core code is not working well, too.

**Comment by nightroman** [comment]
> What do you think about requiring Powershell v5 or newer? The class syntax would really clean up some of this code.

I think classes are buggy and poorly designed. It is up to you but I would not require v5 just because of classes. They are not worth this.

**Comment by nightroman** [comment]
I can see you fixed this
https://github.com/cspotcode/PS-GuiCompletion/commit/ba1aac3

I think this was fixed in my PR as well. But it was a while ago, I cannot be sure.

UPD:

Sorry, I fixed it in another branch `nightroman-2` which I am using for a few months.
Here is the list of its changes:

Further massive improvements and design changes
    - try Use ListItemText for list, remove some preview stuff, use my filter
    - Retire CloseListOnEmptyFilter, Right/Left Arrow
    - Remove LastWord from Select-Item
    - Fix Backspace, remove not used $OldFilter
    - Retire ReturnWord, LastWord
    - Show the current item count in status
    - Remove not used $PowerTabFileSystemMode
    - ***Fix Page Down / Up with not first / last selected***. Review Move-Selection.
    - Use AllowCtrlC in ReadKey to avoid fatal breaks
    - Infer and use common prefix
    - Add margin spaces to filter and status
    - Use one ReadKey
    - Simplify Above / Below

**Comment by nightroman** [comment]
Are we going to merge and publish? It takes too long and my other branch which I actually use diverts too far. I start thinking about maintaining a separate fork repo and module so that users may enjoy some "good stuff" (I honestly think).

Alternatively, we may close this PR and I instead create another PR from even more improved `nightroman-2`. I use it for several years now, it works well.

**Comment by cspotcode** [comment]
I don't have time to work on this anymore, especially since it doesn't work
on Linux.

**Comment by nightroman** [comment]
Fair enough... What do you think about me taking over completely? Options:

1. You transfer the ownership of this repo and PSGallery module to me. I continue from there.
2. I create a permanent fork and new PSGallery module, say, TuiCompletion. You add references to my repo and module in README.

**Comment by cspotcode** [comment]
I've added you as an "owner" on PowerShell Gallery.  That should give you access to publish new versions and update the repository / website information to point to your own github repository.

**Comment by nightroman** [comment]
Thank you, very good, I can see the ownership. Do you prefer to stay the owner or want me to remove you?

Next steps: I create a fork, explain that it is continuation of your work and the future development is in this new repository. Then I add my changes from nightroman-1/2 and publish the new module version with all the details updated. Sounds good?

**Comment by cspotcode** [comment]
Yeah, that all sounds good, and I will update this repository to add links to yours, explain you are the owner, all that stuff.

If it's ok with you, I'd like to remain half-owner on PowerShell Gallery just so I get credit for creating it.  But you have total control of what happens from here on out.

**Comment by nightroman** [comment]
> I create a fork

After some thinking. I would like create a new repository with the same name and push all the previous history instead of creating a fork. From maintenance point of view it's easier for me to separate my own repositories and my temporary forks.

**Comment by cspotcode** [comment]
That sounds good to me.  I agree it will be clearer for everyone if it is not a fork.

**Comment by nightroman** [comment]
> If it's ok with you, I'd like to remain half-owner on PowerShell Gallery just so I get credit for creating it. But you have total control of what happens from here on out.

Yes, absolutely! (I asked just in case.)

**Comment by nightroman** [comment]
New repo -- https://github.com/nightroman/PS-GuiCompletion
It includes the original history and my changes from nightroman-1/2

Please take a look and let me know if something is not quite right.

README includes:

> This repository clones and continues the original [PS-GuiCompletion](https://github.com/cspotcode/PS-GuiCompletion) by [@cspotcode](https://github.com/cspotcode). The published module is the same [GuiCompletion](https://www.powershellgallery.com/packages/GuiCompletion). It is developed here starting from v0.9.0 (coming soon).

We still do not have a license. I am thinking MIT. What was the original PowerTab repo? Is it this -- https://github.com/jasonmarcher/PowerTab ? It uses MIT.

**Comment by cspotcode** [comment]
Any license is fine with me.  I use MIT on my own projects.  I don't remember where the PowerTab code came from unfortunately.

I added a similar header to your repository at the top of the README.  Does it look good to you?  https://github.com/cspotcode/PS-GuiCompletion/#guicompletion-for-powershell

**Comment by nightroman** [comment]
I'll use MIT then.
README header/reference is great, to the point, thank you.
I'll keep this PR opened for discussion until v0.9.0 is released.

**Comment by nightroman** [comment]
GuiCompletion v0.9.0 is released. Thank you for your great tool, work, and cooperation. A few more notes on closing.

- Your new repo About `*Moved to ...` (see top right) formatting is off due to enclosing `*`, and the URL is broken.
- Could you please remove me from collaborators of your repository? In some GH queries it is still kind of mine.

**Comment by cspotcode** [comment]
Done and done!  Since you're no longer a collaborator on this repo, feel free to ping me about closing issues that you have already fixed in your repository, or other administrative tasks like updating links.

**Pull request closed without merging**
